volley_face_homepage:
    pattern:  /
    defaults: { _controller: VolleyFaceBundle:Default:index }

volley_face_admin:
    resource: "@VolleyFaceBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

VolleyFaceBundle_player:
    resource: "@VolleyFaceBundle/Resources/config/routing/player.yml"
    prefix:   /player

VolleyFaceBundle_category:
    resource: "@VolleyFaceBundle/Resources/config/routing/category.yml"
    prefix:   /category

VolleyFaceBundle_post:
    resource: "@VolleyFaceBundle/Resources/config/routing/post.yml"
    prefix:   /post
